services:
  postgres:
    image: postgres:15
    container_name: db_postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mydb
    volumes:
      - postgres-data:/var/lib/postgresql/data

  api:
    build: ./api
    container_name: app_api
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://admin:admin@postgres:5432/mydb
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev # NestJS dev mode

  web:
    build: ./web
    container_name: app_web
    ports:
      - '5173:5173'
    depends_on:
      - api
    volumes:
      - ./web:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev # Vite dev mode

volumes:
  postgres-data:
