version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: nest_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: